name: security-check
on:
  push:
    branches: [ feature/1 ]
  workflow_dispatch:

jobs:
  build-restore:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        nuget: [4.1.0]
    name: NuGet@${{ matrix.nuget }} sample
    steps:
      - uses: actions/checkout@master
      - name: Setup NuGet.exe
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: ${{ matrix.nuget }}
      - run: nuget restore WebGoat.NET.sln
        
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.3.1
        with:
          # Version of Visual Studio to search; defaults to latest if not specified
          vs-version: 16.0
  
  Veracode_Software_Composition_Analisys:
    runs-on: windows-latest
    name: Veracode SCA Scan
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run SCA Scan
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        run: |
          $env:SRCCLR_API_TOKEN
          $env:SRCCLR_API_TOKEN='${{ secrets.SRCCLR_API_TOKEN }}'
          $env:SRCCLR_SCM_URI='https://github.com/lucasferreiram3/WebGoat.Net.git'
          $env:SRCCLR_SCM_REF='${{ github.ref }}'
          $env:SRCCLR_SCM_REF_TYPE='branch'
          $env:SRCCLR_SCM_REV='${{ github.repository_id}}'
          $env:SRCCLR_SKIP_DOTNET_RESTORE=true

          Set-ExecutionPolicy AllSigned -Scope Process -Force

          $ProgressPreference = "silentlyContinue"; iex ((New-Object System.Net.WebClient).DownloadString('https://download.sourceclear.com/ci.ps1'))

          srcclr scan .
  
