name: security-check
on:
  push:
    branches: [ feature/2 ]
  workflow_dispatch:

jobs:
  build-restore:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: nuget_restore
      run: |
        nuget restore WebGoat.NET.sln
   
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - name: Build app for release
      run: msbuild WebGoat.NET.sln -t:rebuild -verbosity:diag -property:Configuration=Release
  
  Veracode_Software_Composition_Analisys:
    runs-on: windows-latest
    name: Veracode SCA Scan
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run SCA Scan
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        run: |
          $env:SRCCLR_API_TOKEN
          $env:SRCCLR_API_TOKEN='${{ secrets.SRCCLR_API_TOKEN }}'
          $env:SRCCLR_SCM_URI='https://github.com/lucasferreiram3/WebGoat.Net.git'
          $env:SRCCLR_SCM_REF='${{ github.ref }}'
          $env:SRCCLR_SCM_REF_TYPE='branch'
          $env:SRCCLR_SCM_REV='${{ github.repository_id}}'
          $env:SRCCLR_SKIP_DOTNET_RESTORE=true

          Set-ExecutionPolicy AllSigned -Scope Process -Force

          $ProgressPreference = "silentlyContinue"; iex ((New-Object System.Net.WebClient).DownloadString('https://download.sourceclear.com/ci.ps1'))

          srcclr scan .
  
